### ISSUE TITLE
Test code for this library?

### ISSUE THREAD

**Issue by limhyon** [PX4/OpticalFlow#4]
Hi,
Is there any test example code for this library available?

-Hyon

**Comment by ChristophTobler** [comment]
You can have a look at the gazebo simulation that uses the optical flow: https://github.com/PX4/sitl_gazebo/blob/master/src/gazebo_opticalFlow_plugin.cpp#L176 (the image argument is now not a `cv::Mat` anymore, but a `uint8_t *img_current`)
Hope this helps.

**Comment by ChristophTobler** [comment]
I updated the README.md which should now show how to use it
