### ISSUE TITLE
Recovering x y velocities in m/s from calcFlow output

### ISSUE THREAD

**Issue by Jamaslab** [PX4/OpticalFlow#5]
Hello,
How can I convert the angular flow (rad/s) in linear velocities (m/s) assuming that the camera stayed on the same plane?

Thank you very much

**Comment by ChristophTobler** [comment]
You just have to scale the angular flow with the distance to the ground. But that only works if you have no rotations -> just translations.

**Comment by ChristophTobler** [comment]
![optical_flow](https://user-images.githubusercontent.com/14769636/28274252-b25c7ca6-6b10-11e7-9645-8107e92049d4.png)
The division by the focal length has already been done here https://github.com/PX4/OpticalFlow/blob/master/src/flow_opencv.cpp#L206-L207 (for small angles division and atan is almost the same)

**Comment by ChristophTobler** [comment]
@Jamaslab feel free to reopen if still unclear

**Comment by EceChaik** [comment]
May I just ask which thesis the above image is from? I'd like to give it a read, thanks.
